dist: trusty
before_install:
    - "sudo apt-get install libunwind8"
    - "make"
language: python
python:
    - "nightly"
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"

script: 
    - "pytest -q tests/"
