dist: trusty
before_install:
    - "sudo apt-get install strace libunwind8"
    - "make"
language: python
python:
    - "nightly"
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
    - "3.2"


install: "pip install -r requirements.txt"
script: 
    - "python tracer.py ls" 
    - "pytest -q tests/"
