dist: trusty
before_install:
    - "sudo apt-get install libunwind8"
    - "make"
language: python
python:
    - "nightly"
    - "3.6"
    - "3.5"
    - "3.4"
    - "3.3"
install: 
    - pip install flake8
    - pip install -r requirements.txt
script: 
    - "flake8 --ignore=E501 tracer"
    - "pytest -q tests/"
