language: python
python:
    - 3.5

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y mercurial
    -  hg clone https://bitbucket.org/MichaelHTW/python-ptrace-withclone /tmp/lib
    - (cd /tmp/lib/; python setup.py install)
    -  openssl aes-256-cbc -K $encrypted_7c4d0fa59f2c_key -iv $encrypted_7c4d0fa59f2c_iv -in .travis_key.enc -out .travis_key -d
    - chmod 600 .travis_key
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


script:
    - python test.py
    - ./test_arm.sh
