#!/bin/bash
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR/.."
LIST="$DIR/list"
REPORT_DIR=/tmp/report1

programs=()
i=1
while read -r line; do
	programs+=($i "$line")
	i=$((i+1))
done < "$LIST"

exec 3>&1
res=$(dialog  --menu "Select program to run " 20 50 30 "${programs[@]}" 2>&1 1>&3)
exec 3>&-
clear

cmd=$(sed "${res}q;d" "$LIST")

rm -rf $REPORT_DIR
eval tracer -b -o "$REPORT_DIR" -- bash -c \""$cmd"\"
tracergui "$REPORT_DIR"
