#!/bin/bash
set -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LIST="$DIR/list"
REPORT_DIR=/tmp/report1

programs=()
i=1
while read -r line; do
	programs+=($i "$line")
	i=$((i+1))
done < "$LIST"

exec 3>&1
res=$(dialog  --menu "Select program to run " 20 50 30 "${programs[@]}" 2>&1 1>&3)
exec 3>&-
clear

cmd=$(sed "${res}q;d" "$LIST")

rm -rf $REPORT_DIR
eval python3 "$DIR/../tracer.py" -b -o /tmp/report1 -- sh -c \""$cmd"\"
python "$DIR/../../gui/app.py" "$REPORT_DIR"
